import type { Metadata } from "next";
import NextUIProviders from "./NextUIProviders";
import "./globals.css";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "Products List",
  description: "A starter generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav></Nav>
        <NextUIProviders>{children}</NextUIProviders>
      </body>
    </html>
  );
}
