import type { Metadata } from "next";
import NextUIProviders from "./NextUIProviders";
import "./globals.css";
import Nav from "@/components/Nav";
import { CartProvider } from "./CartContext";

export const metadata: Metadata = {
  title: "Products List",
  description: "A starter generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProviders>
          <CartProvider>
            <Nav></Nav>
            {children}
          </CartProvider>
        </NextUIProviders>
      </body>
    </html>
  );
}
